spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/db_name
    username: user_name
    password: password
    driver-class-name: org.db.example

  jpa:
    hibernate:
      ddl-auto: update  # <- this is critical for table creation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true



